/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package TimeTester;

import javax.swing.JOptionPane;

/**
 *
 * @author Christian
 */
public class Time_Tester extends javax.swing.JFrame {
    double totalsum = 0;

    /**
     * Creates new form Time_Tester
     */
    public Time_Tester() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTest = new javax.swing.JButton();
        lblTid = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblAL = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblA = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblLL = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblStack = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        snittAL = new javax.swing.JLabel();
        snittA = new javax.swing.JLabel();
        snittLL = new javax.swing.JLabel();
        snittStack = new javax.swing.JLabel();
        lblVenter = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblAnt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTest.setText("Kjør Test");
        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });

        jLabel2.setText("Tidene ble:");

        jLabel1.setText("ArrayList:");

        lblAL.setText("-");

        jLabel3.setText("Array:");

        lblA.setText("-");

        jLabel4.setText("LinkedList:");

        lblLL.setText("-");

        jLabel5.setText("Stack:");

        lblStack.setText("-");

        jLabel6.setText("Snitt:");

        snittAL.setText("-");

        snittA.setText("-");

        snittLL.setText("-");

        snittStack.setText("-");

        lblVenter.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        lblVenter.setText("-");

        btnReset.setText("Reset");

        jLabel7.setText("Antall klikk:");

        lblAnt.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(lblTid)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblVenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAnt)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnTest, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(33, 33, 33)
                                        .addComponent(lblAL))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3))
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblA)
                                            .addComponent(lblStack)
                                            .addComponent(lblLL))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(snittAL)
                                    .addComponent(snittA)
                                    .addComponent(snittLL)
                                    .addComponent(snittStack))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTest)
                    .addComponent(btnReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblAL)
                    .addComponent(snittAL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblA)
                    .addComponent(snittA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblLL)
                    .addComponent(snittLL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblStack)
                    .addComponent(snittStack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVenter)
                    .addComponent(jLabel7)
                    .addComponent(lblAnt))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /*
    ========================================================
    == Her begynner koden skrevet av meg
    ========================================================
    */
    
    private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestActionPerformed
        lblVenter.setText("Legger inn lister, vennligst vent...");
        int ant = 1000000;
        int teller = Integer.parseInt(lblAnt.getText());
        teller += 1;
        lblAnt.setText(Integer.toString(teller));
        
        // Lag en ArrayList
        long startAL = System.nanoTime();
        for(int i = 0; i < ant; i++) {
            Kontroll.kontroll.lagArrayList("per");
        }
        long stopAL = System.nanoTime();
        double totaltidAL = stopAL - startAL;
        double resultatAL = totaltidAL/1000000000;
        String outputAL = String.valueOf(resultatAL);
        lblAL.setText(outputAL);
        
        // Snitt
        totalsum +=   resultatAL;
        double snitt = totalsum/teller;
        String utdata = Double.toString(snitt);
        
        //double snittet = Integer.parseInt(snittAL.getText());
        //snittet +=siste;
        //String snittSomSkalUt = Double.toString(snittet);
        snittAL.setText(utdata.substring(0, 5));
        
       
        
        
        
        // Lag en Array
        long startA = System.nanoTime();
        for(int i = 0; i < ant; i++) {
            Kontroll.kontroll.lagArray("per", i);
        }
        long stopA = System.nanoTime();
        double totaltidA = stopA - startA;
        double resultatA = totaltidA/1000000000;
        String outputA = String.valueOf(resultatA);
        lblA.setText(outputA);
        
        // Lag en LinkedList
        long startLL = System.nanoTime();
        for(int i = 0; i < ant; i++) {
            Kontroll.kontroll.lagLinkedList("per");
        }
        long stopLL = System.nanoTime();
        double totaltidLL = stopLL - startLL;
        double resultatLL = totaltidLL/1000000000;
        String outputLL = String.valueOf(resultatLL);
        lblLL.setText(outputLL);
        
        // Lag en Stack
        long startS = System.nanoTime();
        for(int i = 0; i < ant; i++) {
            Kontroll.kontroll.lagStack("per");
        }
        long stopS = System.nanoTime();
        double totaltidS = stopS - startS;
        double resultatS = totaltidS/1000000000;
        String outputS = String.valueOf(resultatS);
        lblStack.setText(outputS);
        
        lblVenter.setText("Klar");
        // tømer alle lister når vi er ferdige
        Kontroll.kontroll.tømAlleLister();
    }//GEN-LAST:event_btnTestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Time_Tester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Time_Tester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Time_Tester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Time_Tester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Time_Tester().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblAL;
    private javax.swing.JLabel lblAnt;
    private javax.swing.JLabel lblLL;
    private javax.swing.JLabel lblStack;
    private javax.swing.JLabel lblTid;
    private javax.swing.JLabel lblVenter;
    private javax.swing.JLabel snittA;
    private javax.swing.JLabel snittAL;
    private javax.swing.JLabel snittLL;
    private javax.swing.JLabel snittStack;
    // End of variables declaration//GEN-END:variables
}
