

import java.util.LinkedList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Christian
 */
public class VennerGUI extends javax.swing.JFrame {

    /**
     * Creates new form VennerGUI
     */
    public VennerGUI() {
        initComponents();
        
        try {
            Venn nyVenn;
            nyVenn = new Venn("Knut", 12345678);
            Kontroll.kontroll.addVenn(nyVenn);
            nyVenn = new Venn("Ole", 49377544);
            Kontroll.kontroll.addVenn(nyVenn);
            oppdater();
         
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog
                    (rootPane, "Feil ved oppstart: \n" + e.getMessage());
                    
        }
    }
    
   
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNyVennNavn = new javax.swing.JTextField();
        txtNyVennTLF = new javax.swing.JTextField();
        btnRegNyVenn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cmbListe = new javax.swing.JComboBox();
        btnSlett = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cmbTlfListe = new javax.swing.JComboBox();
        txtNyttTlf = new javax.swing.JTextField();
        btnRegNyttTlf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
        );

        jtab.addTab("Venner", jPanel1);

        jLabel1.setText("Navn:");

        jLabel2.setText("Tlf:");

        btnRegNyVenn.setText("Registrer");
        btnRegNyVenn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegNyVennActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegNyVenn)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNyVennNavn, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNyVennTLF, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNyVennNavn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNyVennTLF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnRegNyVenn)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        jtab.addTab("Ny Venn", jPanel2);

        cmbListe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbListe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbListeActionPerformed(evt);
            }
        });

        btnSlett.setText("Slett");
        btnSlett.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlettActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbListe, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSlett)
                .addContainerGap(328, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbListe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSlett))
                .addContainerGap(225, Short.MAX_VALUE))
        );

        jtab.addTab("Slett Venn", jPanel3);

        cmbTlfListe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnRegNyttTlf.setText("Registrer");
        btnRegNyttTlf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegNyttTlfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNyttTlf)
                    .addComponent(cmbTlfListe, 0, 145, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegNyttTlf)
                .addContainerGap(323, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(cmbTlfListe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNyttTlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegNyttTlf))
                .addContainerGap(232, Short.MAX_VALUE))
        );

        jtab.addTab("Endre TLF", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtab)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtab)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegNyVennActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegNyVennActionPerformed
        // TODO add your handling code here:
        regNyVenn();
        txtNyVennNavn.setText("");
        txtNyVennTLF.setText("");
    }//GEN-LAST:event_btnRegNyVennActionPerformed

    private void cmbListeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbListeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbListeActionPerformed

    private void btnSlettActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlettActionPerformed
        // TODO add your handling code here:
        String navn=cmbListe.getSelectedItem().toString();
        Kontroll.kontroll.delVenn(navn);
        
        JOptionPane.showMessageDialog(null, navn + " er slettet");
        oppdater();
        
    }//GEN-LAST:event_btnSlettActionPerformed

    private void btnRegNyttTlfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegNyttTlfActionPerformed
        // TODO add your handling code here:
        String navn=cmbTlfListe.getSelectedItem().toString();
        long tlf = Integer.parseInt(txtNyttTlf.getText());
        Kontroll.kontroll.nyttNr(navn, tlf);
        txtNyttTlf.setText("");
        oppdater();
        
    }//GEN-LAST:event_btnRegNyttTlfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VennerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VennerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VennerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VennerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VennerGUI().setVisible(true);
            }
        });
    }
    
    public void leggTilcmb() {
        
        //Sletter først alt innholdet i begge comboboxene
        int itemCount = cmbListe.getItemCount();
        for(int i=0;i<itemCount;i++){
            cmbListe.removeItemAt(0);
        }
        
        // For endring av tlf
        int teller = cmbTlfListe.getItemCount();
        for(int i=0;i<teller;i++){
            cmbTlfListe.removeItemAt(0);
        }
        
        LinkedList<Venn>venner = Kontroll.kontroll.getVenner();
        
        for(int i=0;i<venner.size();i++) {
            cmbListe.addItem(venner.get(i).getNavn());
            cmbTlfListe.addItem(venner.get(i).getNavn());
        }
    }

     public void oppdater() {
        jTextArea1.setText("");
        
        leggTilcmb(); // Legger til siste innhold i begge boksene
        jTextArea1.append(Kontroll.kontroll.hentAlle());
    }
     
     public void regNyVenn() {
         String navn;
         long tlf;
         
         navn = txtNyVennNavn.getText();
         tlf = Integer.parseInt(txtNyVennTLF.getText());
         
         Kontroll.kontroll.addVenn(new Venn(navn, tlf));
         oppdater();
     }
   
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegNyVenn;
    private javax.swing.JButton btnRegNyttTlf;
    private javax.swing.JButton btnSlett;
    private javax.swing.JComboBox cmbListe;
    private javax.swing.JComboBox cmbTlfListe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTabbedPane jtab;
    private javax.swing.JTextField txtNyVennNavn;
    private javax.swing.JTextField txtNyVennTLF;
    private javax.swing.JTextField txtNyttTlf;
    // End of variables declaration//GEN-END:variables
}
