/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Tjener;
import java.io.*;
import java.net.*;

import javax.swing.JOptionPane;

/**
 *
 * @author Christian
 */
public class Tjener extends javax.swing.JFrame {

    /**
     * Creates new form Tjener
     */
    public Tjener() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(700, 23));

        btnStart.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        btnStart.setText("Start Server");
        btnStart.setAlignmentX(700.5F);
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnStart)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(btnStart)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        
        FileWriter loggfilSkriver = null;
        ServerSocket minServer = null;
        
        btnStart.isSelected();
        try {
            final String filnavn = "loggfil.txt";
            minServer = new ServerSocket(2020);
            boolean avslutt = false;
            String loggpost;
            loggfilSkriver = new FileWriter(filnavn,true);
            
            
            while(!avslutt) { // helt til vi stopper programmet
                // Venter på klient, så lager vi en scket
                Socket minKlient = minServer.accept();
                ObjectInputStream leser = new ObjectInputStream(minKlient.getInputStream());
                loggpost = leser.readUTF();
                
                avslutt = loggpost.equals("STOP");
                loggfilSkriver.write(loggpost + "\n");
                
                // Nå skal vi sende svar tilbake til klienten
                ObjectOutputStream skriver = new ObjectOutputStream(minKlient.getOutputStream());
                skriver.writeUTF("The following har been added to the log:" + "\n" + loggpost);
                
                // Stenger
                skriver.close();
                minKlient.close();
                leser.close();
            }
        } catch (IOException ex) {JOptionPane.showMessageDialog(null, "Problem oppstod hos Server.");}
        finally {
            try {
                minServer.close();
                loggfilSkriver.close();
                    
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Nok en gang hos server...");
            }
        } 
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tjener.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tjener.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tjener.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tjener.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tjener().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    // End of variables declaration//GEN-END:variables
}
