/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Databaser;
import java.awt.HeadlessException;
import static java.lang.Integer.parseInt;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Christian
 */
public class frmDerby extends javax.swing.JFrame {
    

    /**
     * Creates new form frmDerby
     */
    public frmDerby() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        btnSjekk = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtUt = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtRegnr = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNavn = new javax.swing.JTextField();
        txtEier = new javax.swing.JTextField();
        rbtVarm = new javax.swing.JRadioButton();
        rbtKald = new javax.swing.JRadioButton();
        btnRegHest = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbDag = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cmbMnd = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        cmbYear = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPlassering = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        cmbDistanse = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        btnAlleHester = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSjekk.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        btnSjekk.setText("Sjekk Connection");
        btnSjekk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSjekkActionPerformed(evt);
            }
        });

        txtUt.setColumns(20);
        txtUt.setRows(5);
        jScrollPane2.setViewportView(txtUt);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSjekk, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(btnSjekk)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Check Connection", jPanel4);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("ID:");

        txtRegnr.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Navn:");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Eier:");

        txtNavn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        txtEier.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        rbtVarm.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        rbtVarm.setText("Varmblods");

        rbtKald.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        rbtKald.setText("Kaldblods");

        btnRegHest.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        btnRegHest.setText("Registrer");
        btnRegHest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegHestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegHest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbtVarm)
                                .addGap(57, 57, 57)
                                .addComponent(rbtKald))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRegnr, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtNavn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                        .addComponent(txtEier)))))
                        .addGap(0, 158, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRegnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNavn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtVarm)
                    .addComponent(rbtKald))
                .addGap(97, 97, 97)
                .addComponent(btnRegHest)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Registrer hest", jPanel1);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("Dato:");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("Dag:");

        cmbDag.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cmbDag.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setText("Måned:");

        cmbMnd.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cmbMnd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setText("År:");

        cmbYear.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cmbYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2016", "2017" }));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setText("Distanse:");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setText("Plassering:");

        txtPlassering.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jButton2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jButton2.setText("Registrer");

        cmbDistanse.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cmbDistanse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kort", "Middels", "Lang" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbDag, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6)))
                                .addGap(6, 6, 6)
                                .addComponent(cmbMnd, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbDistanse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPlassering, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 45, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbDag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(cmbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbDistanse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPlassering, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104)
                .addComponent(jButton2)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Registrer løpsresultat", jPanel2);

        btnAlleHester.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        btnAlleHester.setText("Vis alle hester");
        btnAlleHester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlleHesterActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jButton3.setText("Hester vs ant løp");

        jButton4.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jButton4.setText("Hester fra kort løp");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAlleHester, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btnAlleHester)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(315, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Rapporter", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane5)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane5)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSjekkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSjekkActionPerformed
        
        // Info om $db
        String url = "jdbc:derby:travhester;create=true"; // Selve basen
        String bruker = "Christian";
        String passord = "passord";
        Connection conn = null;
        Statement setning;
        ResultSet resultat;
        
        
         /*
        ==============================================================
        == Oppretter forbindelse ved oppstart  - Fungerer!
        ==============================================================
        */
        try {
            conn = DriverManager.getConnection(url);
        } catch (SQLException ex) {
            Logger.getLogger(frmDerby.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(conn != null) {
            JOptionPane.showMessageDialog(null, "Forbindelsen er OK");
        }
       // Opprett tabell og utfør
        try {
        String dropString = "drop table hest";
        String createString = "create table hest"
            + "("
            + "regnr int primary key,"
            + "navn varchar(30) not null,"
            + "eier varchar(30),"
            + "varmblods boolean default false"
            + ")";      
        setning = conn.createStatement();
        setning.execute(dropString);
        setning.execute(createString);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog
                    (null, ex.getClass() + "\n" + ex.getMessage() + " FUCK OFF");            
        }
        
        
         /*
        ==============================================================
        == Legger inn testdata ved oppstart
        ==============================================================
        */
        try {
            String insertString = "insert into hest values"
                    + "(1,'Gloppen', 'Per_Olsen', true),"
                    + "(2,'Stallone', 'Ivar_Aasen', false)";
            setning = conn.createStatement();
            setning.execute(insertString);            
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog
                    (rootPane, ex.getClass() + "\n" + ex.getMessage()+ "\n" + "Insert into fungerte ikke");             
        }
        
         /*
        ==============================================================
        == Spørringer mot basen - Fyller inn ved oppstart
        ==============================================================
        */
        try {
            setning = conn.createStatement();
            resultat = setning.executeQuery
                    ("select * from hest order by regnr");
            for (int i=1;i<=resultat.getMetaData().getColumnCount();i++){
                txtUt.append(resultat.getMetaData().getColumnLabel(i) + " ");
            }
            //Vis alle dataene
            txtUt.append("\n");
            while (resultat.next()) {
                txtUt.append(Integer.toString(resultat.getInt("regnr")) + " ");
                txtUt.append(resultat.getString("navn") + " ");
                txtUt.append(resultat.getString("eier") + " ");
                txtUt.append(resultat.getString("varmblods") + " ");
                txtUt.append("\n");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog
                    (rootPane, ex.getClass() + "\n" + ex.getMessage());
        }
        
        /* Lukk forbindelsen */
        try {
            if (conn != null) {
                conn.close();
            }
        } catch (SQLException ex) { JOptionPane.showMessageDialog(rootPane, ex.getClass() + "\n" + ex.getMessage());}   
    }//GEN-LAST:event_btnSjekkActionPerformed

    
    
    
    // Reg av ny hest - Knapp
    private void btnRegHestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegHestActionPerformed
         // Info om $db
        String url = "jdbc:derby:travhester;create=true"; // Selve basen
        String bruker = "Christian";
        String passord = "passord";
        Connection conn = null;
        Statement setning;
        ResultSet resultat;
        
        try {
            conn = DriverManager.getConnection(url);
        } catch (SQLException ex) {
            Logger.getLogger(frmDerby.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            int nr = parseInt(txtRegnr.getText());
            String navn = txtNavn.getText();
            String eier = txtEier.getText();
            String varmblods;
            if(rbtVarm.isSelected()) {
                varmblods = "true";
            } else {
                varmblods = "false";
            }
            String insertString = "insert into hest values"
                    + "(" + nr + ",'" + navn + "', '" + eier + "', " + varmblods + ")";
            setning = conn.createStatement();
            setning.execute(insertString);  
            txtEier.setText(null);
            txtNavn.setText(null);
            txtRegnr.setText(null);
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog
                    (rootPane, ex.getClass() + "\n" + ex.getMessage()+ "\n" + "Insert into fungerte ikke");             
        }
        
        /* Lukk forbindelsen */
        try {
            if (conn != null) {
                conn.close();
            }
        } catch (SQLException ex) { JOptionPane.showMessageDialog(rootPane, ex.getClass() + "\n" + ex.getMessage());}
    }//GEN-LAST:event_btnRegHestActionPerformed

    
    
    
    
    
    
    
    
    
    
    
    
    private void btnAlleHesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlleHesterActionPerformed
         // Info om $db
        String url = "jdbc:derby:travhester;create=true"; // Selve basen
        String bruker = "Christian";
        String passord = "passord";
        Connection conn = null;
        Statement setning;
        ResultSet resultat;
        
        try {
            conn = DriverManager.getConnection(url);
        } catch (SQLException ex) {
            Logger.getLogger(frmDerby.class.getName()).log(Level.SEVERE, null, ex);
        }
        // Legg ut på RAPPORTER
        try {
            StringBuilder ut = new StringBuilder();
            setning = conn.createStatement();
            resultat = setning.executeQuery
                    ("select * from hest order by regnr");
            for (int i=1;i<=resultat.getMetaData().getColumnCount();i++){
                ut.append(resultat.getMetaData().getColumnLabel(i)).append(" ");
            }
            //Vis alle dataene
            ut.append("\n");
            while (resultat.next()) {
                ut.append(Integer.toString(resultat.getInt("regnr"))).append(" ");
                ut.append(resultat.getString("navn")).append(" ");
                ut.append(resultat.getString("eier")).append(" ");
                ut.append(resultat.getString("varmblods")).append(" ");
                ut.append("\n");
            }
            JOptionPane.showMessageDialog(rootPane, ut.toString());
        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog
                    (rootPane, ex.getClass() + "\n" + ex.getMessage());
        }
        
        /* Lukk forbindelsen */
        try {
            if (conn != null) {
                conn.close();
            }
        } catch (SQLException ex) { JOptionPane.showMessageDialog(rootPane, ex.getClass() + "\n" + ex.getMessage());}
     
    }//GEN-LAST:event_btnAlleHesterActionPerformed

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDerby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDerby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDerby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDerby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDerby().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlleHester;
    private javax.swing.JButton btnRegHest;
    private javax.swing.JButton btnSjekk;
    private javax.swing.JComboBox cmbDag;
    private javax.swing.JComboBox cmbDistanse;
    private javax.swing.JComboBox cmbMnd;
    private javax.swing.JComboBox cmbYear;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JRadioButton rbtKald;
    private javax.swing.JRadioButton rbtVarm;
    private javax.swing.JTextField txtEier;
    private javax.swing.JTextField txtNavn;
    private javax.swing.JTextField txtPlassering;
    private javax.swing.JTextField txtRegnr;
    private javax.swing.JTextArea txtUt;
    // End of variables declaration//GEN-END:variables
}
