/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Klient_Tjener;

import java.awt.HeadlessException;
import java.io.*;
import java.net.*;
import java.util.*;
import javax.swing.JOptionPane;
import sun.security.pkcs11.wrapper.Constants;

/**
 *
 * @author Christian
 */
public class Klient extends javax.swing.JFrame {
    TreeMap<Integer, Butler> butlere = new TreeMap<Integer,Butler>();

    /**
     * Creates new form Klient
     */
    public Klient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Liste = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        txtNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbCertified = new javax.swing.JCheckBox();
        btnAddUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jScrollPane1.setViewportView(Liste);

        jLabel1.setText("No:");

        jLabel2.setText("Name:");

        jLabel3.setText("Certified:");

        cbCertified.setText("Yes");

        btnAddUpdate.setText("Add/Update");
        btnAddUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCertified)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbCertified)
                    .addComponent(btnAddUpdate)
                    .addComponent(btnDelete))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings({"unchecked", "unchecked"})
    private void btnAddUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUpdateActionPerformed
        int no = Integer.parseInt(txtNo.getText());
        String name = txtName.getText();
        boolean certified = false;
        if(cbCertified.isSelected()) {
            certified = true;
        }
        Butler nyButler = new Butler(no, name, certified);
        butlere.put(no, nyButler);
        
        // Sender ny informasjon til Tjener/Server
        String sendDenne = ", ADD/UPDATE: " + nyButler.toString();
        send(sendDenne);
        
        
        
        
    }//GEN-LAST:event_btnAddUpdateActionPerformed

    @SuppressWarnings("unchecked")
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        Butler slettMeg = (Butler) Liste.getSelectedValue();
        int slettNo = slettMeg.getNo();
        butlere.remove(slettNo);
        Liste.removeAll();
        Liste.setListData(butlere.values().toArray());
        JOptionPane.showMessageDialog(rootPane, "Butler: " + slettMeg + ", has been deleted.");
        
        // Sender ny informasjon til Tjener/Server
        String sendDenne = ", DELETE: " + slettMeg.toString();
        send(sendDenne);
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int svar = JOptionPane.showConfirmDialog(this, "Shold server close?");
        if (svar == JOptionPane.YES_OPTION) {
            send("STOP");
        }
    }//GEN-LAST:event_formWindowClosing
    
    
    
    public void send(String sendmeg) {
        try {
            Date dato = new Date();
            Socket minServer = new Socket("localhost",2020);
            ObjectOutputStream skriver = new ObjectOutputStream(minServer.getOutputStream());
            skriver.writeUTF(dato.toString() + sendmeg + "\n");
            skriver.flush();
            
            // Leser inn
            ObjectInputStream leser = new ObjectInputStream(minServer.getInputStream());
            sendmeg = leser.readUTF();
            JOptionPane.showMessageDialog(rootPane, sendmeg);
            minServer.close();
            leser.close();
            
            // Null stiller input-felter og fyller listen på nytt
            Liste.removeAll();
            Liste.setListData(butlere.values().toArray());
            txtName.setText(null);
            txtNo.setText(null);
            cbCertified.setSelected(false);
            
        } catch (HeadlessException | IOException ex) {
            JOptionPane.showMessageDialog(rootPane, "Feil i klienten: " + ex.getMessage());
        }
    }
  
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Klient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Klient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Klient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Klient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Klient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList Liste;
    private javax.swing.JButton btnAddUpdate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JCheckBox cbCertified;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNo;
    // End of variables declaration//GEN-END:variables
}
